[slide]
uuid = "f23ea81c-5996-4b7e-aab0-4e9f23b172c2"
title = "PHPerKaigi 2023 のトークン問題でボツにした問題を供養する"
event = "PHP 勉強会@東京 第149 回"
talkType = "LT"
link = "/slides/2023-02-15/phpstudy-tokyo-149/slide.pdf"
tags = [
    "php",
    "phpstudy-tokyo",
]

[[slide.revisions]]
date = "2023-02-15"
remark = "登壇"
