[slide]
uuid = "4cfade4d-8070-43ba-b7a9-48f9d2a1fa3c"
title = "Pure PHP で作る簡易 HTTP サーバ"
event = "PHP カンファレンス香川 2025"
talkType = "レギュラートーク (30分)"
link = "/slides/2025-11-24/phpconkagawa-2025/slides.pdf"
tags = [
    "conference",
    "php",
    "phpconkagawa",
]

[[slide.revisions]]
date = "2025-11-24"
remark = "登壇"
