[locations]
contentDir = "/content"
destDir = "/public"
staticDir = "/static"

[site]
author = "nsfisis"
copyrightYear = 2021

[sites.default]
fqdn = "nsfisis.dev"
siteName = "nsfisis.dev"

[sites.about]
fqdn = "about.nsfisis.dev"
siteName = "nsfisis.dev"

[sites.blog]
fqdn = "blog.nsfisis.dev"
siteName = "REPL: Rest-Eat-Program Loop"
postsPerPage = 10

[sites.slides]
fqdn = "slides.nsfisis.dev"
siteName = "nsfisis’ slides"

[tagLabels]
c = "C"
ci-cd = "CI/CD"
code-golf = "コードゴルフ"
cohackpp = "紅白ぺぱ合戦"
composer = "Composer"
conference = "カンファレンス"
cpp = "C++"
float = "浮動小数点数"
game = "ゲーム"
gitlab = "GitLab"
go = "Go"
http = "HTTP"
isucon = "ISUCON"
macos = "macOS"
mncore-challenge = "MN-Core Challenge"
neovim = "Neovim"
note-to-self = "備忘録"
ouj = "放送大学"
perl = "Perl"
php = "PHP"
phpcon-nagoya = "PHP カンファレンス名古屋"
phpcon-odawara = "PHP カンファレンス小田原"
phpconfuk = "PHP カンファレンス福岡"
phpconkagawa = "PHP カンファレンス香川"
phpconokinawa = "PHP カンファレンス沖縄"
phperkaigi = "PHPerKaigi"
phpkansai = "PHP カンファレンス関西"
phpstudy-tokyo = "PHP 勉強会@東京"
piet = "Piet"
python = "Python"
ruby = "Ruby"
rubykaigi = "RubyKaigi"
rust = "Rust"
scala = "Scala"
scalamatsuri = "ScalaMatsuri"
speedcubing = "ルービックキューブ"
techramen = "TechRAMEN"
trick = "TRICK"
vim = "Vim"
wasm = "WebAssembly"
wireguard = "WireGuard"
ya8 = "Ya8"
yaml = "YAML"
yapc = "YAPC"
zsh = "Zsh"
