[slide]
uuid = "cc51db2d-4f53-4c9c-8930-056e4029e9e0"
title = "浮動小数点数の半開区間で単一値を指定する"
event = "PHP 勉強会@東京 第180回"
talkType = "レギュラートーク (20分)"
link = "/slides/2025-10-29/phpstudy-tokyo-180/slides.pdf"
tags = [
  "php",
  "phpstudy-tokyo",
]

[[slide.revisions]]
date = "2025-10-29"
remark = "登壇"
